version: 0.2

env:
  variables:
    LAMBDA_NAME: "lambda1"  # Change this for different functions

phases:
  install:
    runtime-versions:
      nodejs: 16  # Change based on your Lambda runtime
    commands:
      - echo "Installing dependencies..."
      - cd admin/lambda1
      - npm install  # If using Node.js, remove for Python

  build:
    commands:
      - echo "Zipping function..."
      - zip -r /tmp/lambda1.zip .

  post_build:
    commands:
      - echo "Deploying Lambda function directly..."
      - aws lambda update-function-code --function-name lambda1 --zip-file fileb:///tmp/lambda1.zip
      - echo "Deployment successful!"
