version: 0.2

env:
  variables:
    LAMBDA_NAME: "lambda1"  # Change this if needed

phases:
  install:
    runtime-versions:
      python: 3.9  # Ensure this matches your Lambda runtime
    commands:
      - echo "Installing dependencies..."
      - cd admin/lambda1
      - pip install -r requirements.txt -t .

  build:
    commands:
      - echo "Zipping function..."
      - zip -r /tmp/lambda1.zip .

  post_build:
    commands:
      - echo "Deploying Lambda function directly..."
      - aws lambda update-function-code --function-name lambda1 --zip-file fileb://lambda1.zip
      - echo "Deployment successful!"